EcomProject/urls.py
from django.contrib import admin
from django.urls import path,include # include is compulsory for connecting urls.py file
from django.conf import settings # compulsory to display images in admin panel
from django.conf.urls.static import static # compulsory to display images in admin panel
from accounts.views import register,MyLoginView,MyLogoutView # importing the view (register) which we have created in views.py of accounts
from petsapp.views import pets_list
 
urlpatterns = [
    path('',pets_list,name='home'), # this help if user ipen to site then direct the homepage will open
    path('admin/', admin.site.urls), 
    path('petsapp/',include('petsapp.urls')), # connecting parent (EcomProject) urls.py with petsapp urls.py
    path('register/',register,name='register-page'), # registering the url 
    path('login/',MyLoginView.as_view(template_name="base/login.html"),name='login'), # the syntax is written when in vews.py code is written in class based viewd.
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('cart/',include('cart.urls'),name='cart'),
    path('orders/',include('orders.urls')),
]

if settings: #compulsory to display images in admin panel
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart_home,cart_delete,update_cart # importing views from current directory (.import)
urlpatterns=[
    path('add_to_cart/<int:id>', add_to_cart,name='add_to_cart'),
    path('cartpage',cart_home,name='cartpage'),
    path('cart_delete/<int:id>/',cart_delete,name='cart_delete'),
    path('updatecart/<int:id>/',update_cart,name='updatecart'),
]  

orders/urls.py
from django.urls import path
from .import views
    
app_name="orders"
urlpatterns=[
    path('order_billing',views.place_order,name='order_billing'),
    path('payment/',views.payments,name='payments'),
]

cart/models.py
from django.db import models
from petsapp.models import Pets
from django.contrib.auth.models import User
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=200,blank=True)
    pet=models.ForeignKey(Pets,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    totalprice=models.FloatField(default=0.00)
    timestamp=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='cart_tbl'

cart/views.py
from django.shortcuts import redirect, render
from .models import Cart
from petsapp.models import Pets
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Sum
# Create your views here.

def add_to_cart(request,id): # id is used to fetch the product id
    cart_id=request.session.session_key # this line of the code help to create session in django table session key.
    if cart_id == None:
        cart_id=request.session.create() # if cart id is not enter or create then this line of code help to create session by requesting django to create.
    pet_data=Pets.objects.get(id=id) # fetching id of the product from petapp models.py Pets and pet_data is a variable
    price=pet_data.price
    user_data=request.user # requesting user information
    Cart(cart_id=cart_id,pet=pet_data,user=user_data,totalprice=price).save()
    messages.success(request,"Item Added to Cart Successfully")
    return redirect('/')
 
def cart_home(request):
    all_item=Cart.objects.filter(user=request.user)
    flag=all_item.exists()
    return render(request,'cart/cart_home.html',{'items':all_item,'flag':flag}) # {'items':all_item,'flag':flag} is a key and a value of a dictionary
    
def cart_delete(request,id):
    cart_item=Cart.objects.get(id=id)
    cart_item.delete()
    messages.success(request,"Item Removed From Cart Successfully.")
    return redirect('cartpage') 

def update_cart(request,id):
    p=request.POST.get('price')
    q=request.POST.get('qty')
    p_id=request.POST.get('id')
    total_price=float(p) * int(q)
    Cart.objects.filter(id=p_id).update(quantity=q,totalprice=total_price)
    total_amount=Cart.objects.filter(user=request.user).aggregate(total=Sum('totalprice'))['total'] or 0.00
    return JsonResponse ({'status':True,'totalprice':total_price,'totalamount':total_amount})

cart/templates/cart/cart_home.html
{% include 'base/header.html' %}
    {% block content %}
        <form action="{% url 'orders:order_billing' %}">
        <table class="table table-striped">
            <thead>
                <th scope="col">Pet Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total Price</th>
                <th scope="col">Action</th>
            </thead>

            {% if flag %}
                <tbody>
                    {% for item in items %}
                        <tr>
                            <td>
                                <img src="{{ item.pet.image.url}}" width="100px" height="100">
                                <br/>
                                <h4>{{item.pet.name}}</h4>
                            </td>

                            <td>
                                <input type="number" name="qty" min="0" value="{{item.quantity}}" id="quantity{{item.id}}">
                            </td>

                            <td>
                                {{item.pet.price}}
                            </td>

                            <td>
                                <input type="text" name="price" value="{{ item.totalPrice}}" id="totalprice{{item.id}}" readonly>
                            </td>

                            <td>
                                <a href="{% url 'cart_delete' item.id %}" class="btn btn-danger" data-id={{item.id}}>Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <h4>No item Added in cart....</h4>
                        
                </tbody>
               
            {% endif %}
        </form>
        </table>
        <h4>Total Amount: <span id="totalamount"></span></h4>
        <button type="submit">Proceed to Pay</button>
        <!-- <script>
            $(document).ready(function(){
                localStorage.clear(); // removes any unwanted local storage in system
            
            // Set quantity to 1 and updated total price
            $('input[name="qty"]'),each(function(){
                var id=$(this).closest('tr').find('a').data('id');
                // alert id
                var price= $(this).closest('tr').find('td:nth-child(3)').text();
                var totalprice=parseFloat(price)*1;
                $("#totalprice"+id).val(totalprice.toFixed(2));
                $(this).val(1);
            });
            

            // calculate and update total amount

            function calculatetotalmount(){
                var totalamount=0;
                $('input["qty"]').each(function(){
                var id=$(this).closest('tr').find('a').data('id');
                var quantity=$(this).val();
                var price= $(this).closest('tr').find('td:nth-child(3)').text();
                var totalprice=parseFloat(price)*1;
                $("#totalprice"+id).val(totalprice.toFixed(2));
                totalamount += totalprice;
                });
                $("#totalamount").text(totalamount.toFixed(2));
            }

            // updating quantity and totalprice

            $('input[name="qty"]').change(function(){
                var quantity = $(this).val();
                var price = $(this).closest('tr').find('td:nth-child(3)').text();
                var id = $(this).closest('tr').find('a').data('id');
            
                $.ajax({
                    url : '/cart/updatecart/' + id +'/',
                    method:'POST',
                    data:{'qty':quantity,'price':price,'csrfmiddlewaretoken':'{{csrf_token}}'},
                    success:function(response){
                        $('#totalprice'+id).val(response.totalprice);
                        CalculateTotalAmount();// call the function
                    },
                    error:function(){
                        alert("Some Issue in code.")
                    }
                });
            });

            CalculateTotalAmount(); //quantity
        </script>
     -->


<script>
    $(document).ready(function(){
        $('form').submit(function(e){
            e.preventDefault(); //preventing submiit the form
            var totalamount=parseFloat($("#totalamount").text()).toFixed(2); //total amount
            window.location.href=$(this).attr('action')+'?totalamount='+totalamount;
        });
        //localStorage.clear();
    
        $('input[name="qty"]').each(function(){
            var id = $(this).closest('tr').find('a').data('id');
            var price = $(this).closest('tr').find('td:nth-child(3)').text();
            var totalprice = parseFloat(price) * 1;
            $("#totalprice"+id).val(totalprice.toFixed(2));
            $(this).val(1);
        });
    
        // Calculate and update the total amount
        function CalculateTotalAmount(){
            var totalamount = 0;
            $('input[name="qty"]').each(function(){
                var id = $(this).closest('tr').find('a').data('id');
                var quantity = $(this).val();
                var price = $(this).closest('tr').find('td:nth-child(3)').text();
                var totalprice = parseFloat(price) * quantity;
                $("#totalprice"+id).val(totalprice.toFixed(2));
                totalamount += totalprice;
    
            });
            $("#totalamount").text(totalamount.toFixed(2));
        }
    
        $('input[name="qty"]').change(function(){
            var quantity = $(this).val();
            var price = $(this).closest('tr').find('td:nth-child(3)').text();
            var id = $(this).closest('tr').find('a').data('id');
    
            $.ajax({
                url: '/cart/updatecart/' + id + '/',
                method: 'POST',
                data: {'qty': quantity, 'price': price,'id':id, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                success: function(response){
                    $('#totalprice'+id).val(response.totalprice);
                    CalculateTotalAmount(); // call the function
                },
                error: function(){
                    alert("Some issue in the code.");
                }
            });
        });
    
        CalculateTotalAmount();
    });
</script>



    {% endblock %}
{% include 'base/footer.html' %}